// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSZoakamAeMu1SKY3BNJx9PlJYWDFbgx8',
    appId: '1:47011811529:web:e6cccdf9111cd4c5dffd18',
    messagingSenderId: '47011811529',
    projectId: 'safebite-c7925',
    authDomain: 'safebite-c7925.firebaseapp.com',
    storageBucket: 'safebite-c7925.firebasestorage.app',
    measurementId: 'G-0WTY0BMKMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdYyb4yCRMZFBnZBJxbPaZCVMVKHs-Hk',
    appId: '1:47011811529:android:6d16605a94dc1075dffd18',
    messagingSenderId: '47011811529',
    projectId: 'safebite-c7925',
    storageBucket: 'safebite-c7925.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeAnL2cgGTZjQ5sINL7-6Gmbuop2rNBqE',
    appId: '1:47011811529:ios:6d4eda2a6dee8d47dffd18',
    messagingSenderId: '47011811529',
    projectId: 'safebite-c7925',
    storageBucket: 'safebite-c7925.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeAnL2cgGTZjQ5sINL7-6Gmbuop2rNBqE',
    appId: '1:47011811529:ios:6d4eda2a6dee8d47dffd18',
    messagingSenderId: '47011811529',
    projectId: 'safebite-c7925',
    storageBucket: 'safebite-c7925.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSZoakamAeMu1SKY3BNJx9PlJYWDFbgx8',
    appId: '1:47011811529:web:b64b08ea7ebf2041dffd18',
    messagingSenderId: '47011811529',
    projectId: 'safebite-c7925',
    authDomain: 'safebite-c7925.firebaseapp.com',
    storageBucket: 'safebite-c7925.firebasestorage.app',
    measurementId: 'G-PKSWGEGRBH',
  );
}
